# Generated by Django 6.0.7 on 2026-08-06 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='source_language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('hi', 'Hindi'), ('te', 'Telugu')], max_length=10),
        ),
        migrations.AlterField(
            model_name='translation',
            name='target_language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('hi', 'Hindi'), ('te', 'Telugu')], max_length=10),
        ),
    ]
