# Generated by Django 6.0.7 on 2026-08-06 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0002_alter_translation_source_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
